### ISSUE TITLE
ascomycota example

### ISSUE THREAD

**Issue by LunaSare** [McTavishLab/physcraper_example#3]
```
(venv-physcraper) [lsanchezreyes2@merced physcraper_example]$ auto_scrape.py -s pg_238 -t tree109 -o pg_238
https://treebase.org/treebase-web/search/downloadAStudy.html?id=2137&format=nexml
downloading best match alignment from treebaseget_mrca_ott
(v3) MRCA of sampled taxa is Fungi
No config file, using defaults
Using default configuration
created physcraper ncbi_mrca 4751,
434 taxa in alignment and tree
call align query seqs from est full tree, self._blast_read is 0
blast dir is /home/lsanchezreyes2/repos/physcraper_example/pg_238/current_blast_run
run_blast_wrapper
/home/lsanchezreyes2/repos/physcraper_example/pg_238/current_blast_run
blasting seq otu63372
txid4751[orgn]
blasting /home/lsanchezreyes2/repos/physcraper_example/pg_238/current_blast_run/otu63372.xml using webservice
blasting seq otu63373
txid4751[orgn]
blasting /home/lsanchezreyes2/repos/physcraper_example/pg_238/current_blast_run/otu63373.xml using webservice
Traceback (most recent call last):
  File "/home/lsanchezreyes2/repos/physcraper/venv-physcraper/bin/auto_scrape.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lsanchezreyes2/repos/physcraper/bin/auto_scrape.py", line 57, in <module>
    scraper.est_full_tree()
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/scrape.py", line 1054, in est_full_tree
    alignment = self.align_query_seqs()
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/scrape.py", line 902, in align_query_seqs
    self.read_blast_wrapper()
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/scrape.py", line 515, in read_blast_wrapper
    self.run_blast_wrapper()
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/scrape.py", line 271, in run_blast_wrapper
    self.run_web_blast_query(query, equery, fn_path)
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/scrape.py", line 211, in run_web_blast_query
    hitlist_size=self.config.hitlist_size)
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/AWSWWW.py", line 142, in qblast
    rid, rtoe = _parse_qblast_ref_page(handle)
  File "/home/lsanchezreyes2/repos/physcraper/physcraper/AWSWWW.py", line 242, in _parse_qblast_ref_page
    raise ValueError("Error message from NCBI: %s" % msg)
ValueError: Error message from NCBI: Message ID#29 Error: Query string not found in the CGI context
```

**Comment by snacktavish** [comment]
Due to blasting all gap sequences! Fixed in commit https://github.com/McTavishLab/physcraper/commit/7e65b85dd01d7d2a43e3e89ba309971815334a56
